config/merge.lua
* Removed Leech Poison (Changed in 6.1 to a Leech stat bonus)
* Added Combat Rogue perk 'Swift Poison'
* Merge Killing Spree 'offhand' attacks into main hand and merge attacks from the duration of it.
=> Rogue Changes:

config/merge.lua
- Review of Mage for WoD. Tested all changes on all 3 specs.
- Added WoD Weapon Enchant "Shattered Hand"
=> Mage Changes + Weapon Enchant

config/merge.lua
Protection / Ret Paladin clean up. Tested.
Order got changed for no reason at all - was testing various things.
=> Protection / Ret Paladin clean up. Tested.

config/merge.lua
=> Monk / Warrior Class Cleanup

modules/combattext.lua
_G.Currency changed to _G.CURRENCY
=> Fixed a typo

config/merge_class.lua
Major bug avoided! :)
-- Torch
=> 1 Spacing error. It bothered me!

config/merge_class.lua, config/merge_wod.lua
- Guardian Druid merges
- Balance Druid T18 2P
=> Druid Merges

config/merge_class.lua
I don't know enough about git to even understand how i am 5 commits ahead of the main fork with just merging in 1 change but ok :)
=> Added Breath of Fire (Monk, Brewmaster) DoT

config/merge_class.lua, config/merge_legion.lua
=> Monk + World Quest Adjustments

config/merge_class.lua, config/merge_legion.lua
- Merge Greater Blessing of Might (Paladin)
- Merge Flying Serpent Kick (Monk)
- Merge Spiked Counterweight (Melee Trinket)
- Merge 'The Monkey King' SCK (Monk Follower)
=> Monk / Paladin / Trinket Merges

config/merge_legion.lua
- Paladin, Arator the Redeemer Bodyguard Merges
- World Quests, PvP Warden Tower's Powder Keg
=> Paladin Bodyguard + PvP Warden Tower Powder Keg Merge

config/merge_class.lua, config/merge_legion.lua, config/merge_mop.lua, config/merge_wod.lua
- Class: Rogue, Warlock and Paladin changes.
- Legion: Added 2x Trinkets, 2x DPS Potions (Old War has wrong icon so gave it correct one)
- merge_legion.lua: Cleaned up. Gave it some 'standards' love
- merge_legion.lua: Gave 'Consumables' their own category
- merge_mop.lua: Adjusted CreateMergeHeader to match clean up in merge_legion.lua
- merge_wod.lua: Adjusted CreateMergeHeader to match clean up in merge_legion.lua
=> Many Whelps (Changes)! Handle It!

config/merge_class.lua, config/merge_legion.lua
merge_class: Paladin + Monk
merge_legion: less blank lines
=> merge_class / merge_legion changes

config/merge_class.lua, config/merge_legion.lua
- merge_legion: Added Trinket (Oakheart's Gnarled Root)
- merge_legion: clean up (I have an idea how to make this look more sexy)
- merge_class: Paladin Artifact Healing Storm
- merge_class: Paladin clean up
- merge_class: Priest (Mind Spike removed in 7.1.5)
=> Trinket, Paladin and Priest Changes

config/merge_class.lua, config/merge_legion.lua
- merge_class.lua: Add 2x Paladin Talents
- merge_legion.lua: Druid Order Hall Item "Thornstalk Barbs"
=> Paladin / Druid spell merges

config/merge_class.lua, config/merge_legion.lua
merge_class.lua: Warlock / Sub Rogue adjustments (might of missed man…y things in beta ...)
merge_legion.lua: Trinket - Draught of Souls
=> Warlock / Rogue / NH Trinket

config/merge_class.lua, config/merge_legion.lua
merge_class: Frost Mage / Demo Warlock
merge_legion: Nighthold Trinkets + Mage Bodyguard
=> Trinkets, Mage and Warlock Merges

config/merge_class.lua, config/merge_init.lua, config/merge_legion.lua, config/merge_mop.lua, config/merge_other.lua, config/merge_wod.lua, config/profile.lua, core.lua, init.lua, libs/xCombatParser-1.0/example.lua, libs/xCombatParser-1.0/xCombatParser-1.0.lua, media/colors.lua, media/media.lua, modules/blizzard.lua, modules/combattext.lua, modules/frames.lua, modules/grid.lua, modules/include.xml, modules/options.lua, xCT+.toc
Updates xCT+ to work with new API changes for WoW 8.0+.
=> BfA Prepatch update

config/include.xml, config/merge_allied_race.lua, config/merge_bfa.lua, config/merge_class.lua, config/merge_init.lua, core.lua, modules/options.lua
Added Racial Tab for Racial spell 
(containing only void elf at the moment, code may not be as good as yours because i'm not good at lua :) and i still had troubles understanding the whole mechanics of the code )
Added multiple spells for DK/warlock/priests/mage/hunter
Included Znuff patches
=> Racial Tab + Some spells 

config/merge_class.lua, config/merge_shadowlands.lua
=> Some Shadowlands improvements

modules/frames.lua
=> Add simple check if frame is disabled

config/merge_allied_race.lua, config/merge_class.lua, config/merge_shadowlands.lua
Tried my best,
But still have to find time to do a cleanup on the spells of the classes i use :)
=> Spell update for some classes

xCT+.toc
Fixes https://github.com/dandruff/xCT/issues/244
=> Prepare TOC for TWW
